<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'OrderManagement\Module'                        => __DIR__ . '/Module.php',
    'OrderManagement\Controller\OrderManagementController' => __DIR__ . '/src/OrderManagement/Controller/OrderManagementController.php',
    'OrderManagementTest\Framework\TestCase'        => __DIR__ . '/tests/OrderManagement/Framework/TestCase.php',
    'OrderManagementTest\SampleTest'                => __DIR__ . '/tests/OrderManagement/SampleTest.php',
);
